version: '2'
services:
  instance:
    container_name: etcd-announcer
    build:
      context: .
      args:
        - docker_gid
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: bridge

# vim: set ts=2 sts=2 sw=2 et:
